### ISSUE TITLE
GPL license violation

### ISSUE THREAD

**Issue by cerebis** [dyxstat/ViralCC#5]
This is quite possibly an oversight by the authors of ViralCC, but I want to make you aware that the ViralCC repository violates the terms of the GPL and steps should be taken to rectify the issue.

Let me explain.

I am the author of [bin3C](/cerebis/bin3C) and [proxigenomics_toolkit](/cerebis/proxigenomics_toolkit), and I happened to notice today that code has been copied from proxigenomics_toolkit and slightly modified or simplified and made part of ViralCC.

In a non-exhaustive inspection, I found Sparse2DAccumulator and sections of ContactMap.

First, I want to say, great to see! However, use in this way is only acceptable if the two criteria I outline below are met.

As encouragement, I want to point out that if we don't meet the obligations of the licenses we stick on our projects, the process has little value.

### 1. You must make an attribution.

The following is taken from [a highly rated answer on Stack Exchange](https://opensource.stackexchange.com/questions/4577/does-gplv3-require-attribution)

---

So if I modify source that had `Copyright (c) 2016 Amani Kilumanga` I shall not remove that copyright statement. I can add my copyright statement `Copyright (c) 2016 Philippe Ombredanne` and I must state that I modified the source when and how.

For instance I could add this change notice: `2016-10-01: Update the interactive streamline nosql to supply strategic users`.

If the source code was missing a proper GPL notice, I shall add it and I would use the provided [example](https://www.gnu.org/licenses/gpl-3.0.html#howto) as a template.

So in all cases, the modified source code would start with something more or less like this:
I cannot find any mention of the source of the work.

```
Copyright (c) 2016 Amani Kilumanga
Modifications Copyright (c) 2016 Philippe Ombredanne
2016-10-01: Update the interactive streamline nosql to supply strategic users

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>.
```

---

### 2. You cannot relicense the code with an incompatible license.

PGT is licensed under **GPL3 Affero**, which adds constraints with regard to software run on servers. As such, the standard GPL3 and GPL3 Affero are "copyleft" incompatible. That is to say, derivative work cannot remove constraints by issuing their work under a different licence. Normally, this is dealt with by simply adopting the same license or choosing one which is compatible.

See https://www.gnu.org/licenses/license-compatibility.en.html

**Comment by dyxstat** [comment]
Hi Dr. DeMaere,

I sincerely appreciate your suggestions and apologize that I did not know about the license issue before.

For your first comment, we add the copyright statement in https://github.com/dyxstat/ViralCC/blob/main/construct_graph.py as

'''
Copyright (c) 2019 Matthew Z. DeMaere
Modifications Copyright (c) 2022 Yuxuan Du
2022-03-05: The class Sparse2DAccumulator and ContactMatrix were modified from https://github.com/cerebis/bin3C.

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>.
'''.

For the second problem, I am a little bit confused. Is it OK I replace the orginal license by [AGPL-3.0 license](https://github.com/dyxstat/ViralCC#AGPL-3.0-1-ov-file)?

Best,
Yuxuan
