### ISSUE TITLE
Retrieve virus-host pairs with ViralCC

### ISSUE THREAD

**Issue by Kenkeni-ZJU** [dyxstat/ViralCC#6]
Hi Yuxuan,

I am trying to retrieve virus-host pairs with ViralCC since it seems that I can do this (according to your paper). However, there is no such information in the output files. Can I achieve this goal directly with ViralCC?

Thanks,
Kankan

**Comment by dyxstat** [comment]
Hi Kankan,

The ViralCC software serves as a binning tool for viral contigs. To replicate the results regarding virus-host interactions presented in our paper, you'll then need to bin non-viral contigs using your preferred binning tools and generate the raw Hi-C contact matrix for all contigs including viral and non-viral contigs (tools like [NormCC](https://github.com/dyxstat/MetaCC) can facilitate this process).

Utilizing both the raw Hi-C contact matrix and the identified viral as well as non-viral bins, you can then discern the viral-host pairs.

Best

**Comment by Kenkeni-ZJU** [comment]
Thank you!

**Comment by DeaconOfBiology** [comment]
Hi @dyxstat,

Thank you for developing these tools, they’ve been very helpful as I begin working with Hi-C metagenomics.

I’ve used MetaCC and ViralCC to generate MAGs and vMAGs from my Hi-C datasets, and I’m now looking to perform virus-host pairing, as described in your ViralCC paper. You mentioned that combining the raw Hi-C contact matrix with viral and non-viral bins allows one to identify these interactions.

I have the raw Hi-C contact matrices and the bins, but I’m unsure how to proceed with identifying the virus-host pairs in a way consistent with your manuscript. Would you be willing to share any scripts (Python, R, etc.) or additional guidance on how you carried out this part of the analysis?

Any advice or resources you can provide would be greatly appreciated.

Best regards,
TJ
